[relaychain]
default_command = "{{ZOMBIENET_RELAYCHAIN_COMMAND}}"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "relay1"
  ws_port = 9944
  validator = true

  [[relaychain.nodes]]
  name = "relay2"
  validator = true

[relaychain.genesis.runtimeGenesis.patch.configuration.config]
scheduling_lookahead = 2

[relaychain.genesis.runtimeGenesis.patch.configuration.config.async_backing_params]
max_candidate_depth = 3
allowed_ancestry_len = 2

[[parachains]]
id = 2900
cumulus_based = true
chain = "klaos-local-v"

  [[parachains.collators]]
  name = "ownership"
  ws_port = 9999
  command = "{{ZOMBIENET_OWNCHAIN_COMMAND}}"
  validator = true
  args = ["-ldebug"]

  [[parachains.collators]]
  name = "ownership-1"
  ws_port = 10000
  command = "{{ZOMBIENET_OWNCHAIN_COMMAND}}"
  validator = true

[[parachains]]
id = 2008
cumulus_based = true
chain = "astar-dev"

  [[parachains.collators]]
  name = "astar"
  ws_port = 9998
  command = "{{ZOMBIENET_ASTAR_COMMAND}}"
  validator = true
  args = ["-lxcm=trace,debug"]
